---

- name: dotnet
  community.general.pacman:
     name:
      - dotnet-runtime
      - dotnet-sdk
     state: present

- name: node
  community.general.pacman:
     name:
      - nodejs
      - npm
     state: present

- name: install n
  npm: 
    name: n
    global: true

- name: Node 14
  shell: n 14

- name: Install Angular.js
  npm:
    name: "@angular/cli@15"
    global: yes
    state: present


- name: entity framework tools
  ansible.builtin.shell:
    cmd: dotnet tool install --global dotnet-ef
  ignore_errors: true
  


- name: dbeaver
  ansible.builtin.shell:
    cmd: yay -S dbeaver --noconfirm
  ignore_errors: true

- name: postman
  ansible.builtin.shell:
    cmd: yay -S postman-bin --noconfirm
  ignore_errors: true
  become: False


- name: Obsidian, Vscode
  pacman:
    name:
      - obsidian
      - code
    state: present


- name: Pyenv
  ansible.builtin.git:
    repo: https://github.com/pyenv/pyenv.git
    dest: ~/.pyenv
    single_branch: yes
    version: master


- name: Rust
  shell:
    cmd: curl https://sh.rustup.rs -sSf | sh