---

- name: Day 2 Day programs
  community.general.pacman:
   name: 
    - thunderbird
    - bitwarden
    - qbittorrent
    - discord
    - brave
    - fireshot
   state: present 


- name: zoom
  ansible.builtin.shell:
    cmd: yay -S zoom --noconfirm
  ignore_errors: true

- name: audacity
  ansible.builtin.shell:
    cmd: yay -S audacity --noconfirm
  ignore_errors: true

- name: iriun webcam
# sudo rmmod v4l2loopback; sudo modprobe v4l2loopback exclusive_caps=1
  ansible.builtin.shell:
    cmd: yay -S iriunwebcam-bin  --noconfirm
  ignore_errors: true


# later on copy the profile